import { useEffect, useMemo, useState } from 'react';
import Navbar from './components/Navbar';
import Hero from './components/Hero';
import Projects from './components/Projects';
import ProjectModal from './components/ProjectModal';
import Skills from './components/Skills';
import About from './components/About';
import Gallery from './components/Gallery';
import Footer from './components/Footer';
import { projects } from './data/projects';

const specialDetails = {
  en:{ethereum:{eyebrow:'BLOCKCHAIN ANALYTICS · TEAM RESEARCH PROJECT',title:'Ethereum Token Risk Classification',body:<><section className="ethereum-detail-section"><h3>01 / Key finding</h3><p>Spam tokens were more likely to cluster within a narrow block window and show concentrated distribution patterns.</p><p><b>34.0%</b> of spam tokens were active in only one block, compared with <b>7.2%</b> of legitimate tokens.</p><figure className="ethereum-bar-chart" aria-label="Tokens active in only one block"><figcaption>Tokens active in only one block</figcaption><div className="ethereum-bars"><div className="ethereum-bar-item"><span className="bar-value">7.2%</span><div className="bar-track"><i className="bar legitimate-bar"/></div><span className="bar-label">Legitimate</span></div><div className="ethereum-bar-item"><span className="bar-value">34.0%</span><div className="bar-track"><i className="bar spam-bar"/></div><span className="bar-label">Spam</span></div></div></figure></section><section className="ethereum-detail-section"><h3>02 / Method</h3><p>Symbol collisions were used to construct training labels, not as model inputs. The classifier learned on-chain behavior rather than memorizing the labeling rule.</p></section><aside className="ethereum-research-note"><h3>Research note</h3><p>We also tested semi-supervised expansion with approximately 8,750 unlabeled tokens, but it did not improve performance. Distribution shift and pseudo-label noise made the supervised model more reliable.</p></aside><section className="ethereum-detail-section"><h3>03 / Team contribution</h3><p>Team project. I contributed across the research pipeline—from problem framing and label construction to feature engineering, model comparison, and interpretation.</p></section></>},iqiyi:{eyebrow:'02 / AUDIENCE INTELLIGENCE',title:'How I structured the research',body:<><p>Rather than looking only at overall preference, I compared content, audiences, and pathways together.</p>{[['01 Content preference','Compared awareness, viewing interest, and preferences across Asian dramas, short-form dramas, animation, and AI content.'],['02 Audience segmentation','Cross-analyzed country, age, membership status, and ethnicity to identify where the same content carries different value.'],['03 Growth pathways','Examined how people discover content and how that interest connects to iQIYI touchpoints.']].map(x=><section className="iqiyi-modal-step" key={x[0]}><h3>{x[0]}</h3><p>{x[1]}</p></section>)}<section className="iqiyi-modal-output"><h3>Output</h3><p>Synthesized the analysis into a research report to inform English-region content selection, off-platform discovery, and product consideration.</p></section></>}},
  zh:{ethereum:{eyebrow:'BLOCKCHAIN ANALYTICS · 团队研究项目',title:'以太坊代币风险识别',body:<><section className="ethereum-detail-section"><h3>01 / 主要发现</h3><p>Spam token 往往在较短的区块窗口内集中活动，并呈现更集中的分发结构。</p><p><b>34.0%</b> 的 spam token 仅活跃于一个区块；对应的 legitimate token 为 <b>7.2%</b>。</p><figure className="ethereum-bar-chart" aria-label="仅活跃于一个区块的代币比例"><figcaption>仅活跃于一个区块的代币比例</figcaption><div className="ethereum-bars"><div className="ethereum-bar-item"><span className="bar-value">7.2%</span><div className="bar-track"><i className="bar legitimate-bar"/></div><span className="bar-label">Legitimate</span></div><div className="ethereum-bar-item"><span className="bar-value">34.0%</span><div className="bar-track"><i className="bar spam-bar"/></div><span className="bar-label">Spam</span></div></div></figure></section><section className="ethereum-detail-section"><h3>02 / 方法说明</h3><p>同名冲突规则只用于构造训练标签，并未被作为模型特征输入。模型学习的是链上行为，而不是直接记住标签规则。</p></section><aside className="ethereum-research-note"><h3>研究注记</h3><p>团队还尝试利用约 8,750 个未标注 token 进行半监督扩充，但没有改善结果。未标注样本与已有标签的行为分布不同，伪标签会带入额外噪声，因此未被采用。</p></aside><section className="ethereum-detail-section"><h3>03 / 团队贡献</h3><p>团队项目；我参与了从问题定义、标签构建、特征工程到模型比较与结果解释的完整研究流程。</p></section></>},iqiyi:{eyebrow:'02 / 受众洞察',title:'我如何组织这次分析',body:<><p>不是只看整体偏好，而是同时比较内容、人群与路径：</p>{[['01 内容偏好','比较亚洲剧、微剧、动漫及 AI 内容的观看兴趣、认知与偏好差异。'],['02 受众分层','按国家、年龄、会员状态和族裔交叉拆分，识别同一内容对不同人群的意义。'],['03 增长承接','进一步查看用户通过哪些渠道发现内容，以及内容兴趣如何与 iQIYI 的产品触点连接。']].map(x=><section className="iqiyi-modal-step" key={x[0]}><h3>{x[0]}</h3><p>{x[1]}</p></section>)}<section className="iqiyi-modal-output"><h3>研究产出</h3><p>将上述分析整理为面向英语地区内容与运营讨论的研究报告，为内容选型、站外触达与产品承接提供参考。</p></section></>}}
};

export default function App(){
  const [language,setLanguage]=useState(()=>localStorage.getItem('portfolio-language')==='zh'?'zh':'en');
  const [modalKey,setModalKey]=useState(null);
  useEffect(()=>{document.documentElement.lang=language==='zh'?'zh-CN':'en';localStorage.setItem('portfolio-language',language)},[language]);
  const detail=useMemo(()=>modalKey?{...projects[language],...specialDetails[language]}[modalKey]:null,[modalKey,language]);
  return <><div className="grain"/><Navbar language={language} onToggle={()=>setLanguage(v=>v==='en'?'zh':'en')}/><main id="top"><Hero language={language}/><Projects language={language} onOpen={setModalKey}/><Skills language={language}/><About language={language}/><Gallery language={language}/></main><Footer language={language}/><ProjectModal detail={detail} onClose={()=>setModalKey(null)}/></>;
}
